//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LT.DigitalOffice.ClaimService.Validation.Claim.Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ClaimEditRequestValidatorRsourses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClaimEditRequestValidatorRsourses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LT.DigitalOffice.ClaimService.Validation.Claim.Resourses.ClaimEditRequestValidato" +
                            "rRsourses", typeof(ClaimEditRequestValidatorRsourses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Closed.
        /// </summary>
        internal static string ClaimClosed {
            get {
                return ResourceManager.GetString("ClaimClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First symbol of name can not bbe a special symbol..
        /// </summary>
        internal static string FirstCharacterIsNotSpecialName {
            get {
                return ResourceManager.GetString("FirstCharacterIsNotSpecialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Deadline format..
        /// </summary>
        internal static string IncorectDeadLineFormat {
            get {
                return ResourceManager.GetString("IncorectDeadLineFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Claim Priority..
        /// </summary>
        internal static string IncorrectClaimPriority {
            get {
                return ResourceManager.GetString("IncorrectClaimPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Claim Status..
        /// </summary>
        internal static string IncorrectClaimStatus {
            get {
                return ResourceManager.GetString("IncorrectClaimStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only claim creator can choose these statuses..
        /// </summary>
        internal static string IncorrectUser {
            get {
                return ResourceManager.GetString("IncorrectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content musn&apos;t be empty..
        /// </summary>
        internal static string NotEmptyContent {
            get {
                return ResourceManager.GetString("NotEmptyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name mustn&apos;t be empty..
        /// </summary>
        internal static string NotEmptyName {
            get {
                return ResourceManager.GetString("NotEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotExistingCategoryId..
        /// </summary>
        internal static string NotExistingCategoryId {
            get {
                return ResourceManager.GetString("NotExistingCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content can not be longer than 2000 symbols..
        /// </summary>
        internal static string TooLongContent {
            get {
                return ResourceManager.GetString("TooLongContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can not bbe longer than 100 symbols..
        /// </summary>
        internal static string TooLongName {
            get {
                return ResourceManager.GetString("TooLongName", resourceCulture);
            }
        }
    }
}
